### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by caillou** [unic/estatico#22]
Tests are broken in `master`.

```
/Users/caillou/Projects/estatico/node_modules/gulp-raster/lib/converter.js:27
            .done(function (img) {
             ^

TypeError: phantomProcess.then(...).done is not a function
```

**Comment by caillou** [comment]
OK, seems like installing the dependencies with `npm` rather than `yarn` fixes that issue. Sorry about that.

This being said, ideally we should move forward with with our time and keep an evergreen repository.

**Comment by backflip** [comment]
Yarn will not properly resolve git commits in dependencies. We'll have to work around this with tags.

**Comment by backflip** [comment]
What do you mean by "evergreen repository"?

**Comment by caillou** [comment]
Things kept green ;) E.g. using https://greenkeeper.io/

Staying up to date with dependencies.

**Comment by backflip** [comment]
Ah, I see. However, it's not a production environment, so we have way less interest in spending a lot of time keeping everything up-to-date (compared to an environment where it would be a security risk not to do it). And this specific use-case would have still failed with Greenkeeper since it's a Yarn issue.

But we'll definitely give this some more thought, thanks for the pointer!
