### ISSUE TITLE
[Suggestion] Use up-to-date node version in package.json

### ISSUE THREAD

**Issue by Swissbite** [unic/estatico#92]
`package. json` contains an old version as a minimum requirement for NodeJS and even the definition in `.nvmrc` is far behind.

I would suggest updating it and setting up a current `.nmvrc`, `.npmrc` and an equivalent version for `.node-version` and `.npm-version` (used by nodist on Microsoft Windows).

If you don't want to keep `.nmvrc` and `.npmrc` up to date, I recommend to remove both files and to limit the NodeJS version in package. json deliberately.

**Comment by backflip** [comment]
@Swissbite, thanks a bunch for your input!

The versions are outdated since the current code does only run there. However, the new setup is optimized for the current LTS (8) as well as the latest version (9): https://github.com/unic/estatico-nou

With regards to `.npmrc`: Do you see an upside in this? I have never had any issues with `npm` in new node versions and was under the impression the bundled versions were perfectly fine.

Regarding `.node-version`: Do you know how common `nodist` is? We are currently recommending `nvm-windows` instead.

**Comment by Swissbite** [comment]
@backflip There are 3 major nvm version managers for windows.
In History: 
- nvmw - About 600 stars, but no longer maintained.
- nodist - About 850 stars, still maintained. Better support of shell (cmd, powershell). Is more like nvm on unix / linux. 
- nvm-windows - About 5,1 k stars, still maintained. Do not compare it with nvm for unix systems. It works different, sets the node version on global level.

As a windows user I would suggest to either manage both definitions or none of them. Nevertheless they should be in sync the `package.json` definition.

**Comment by backflip** [comment]
Slighly delayed: I disagree that the versions should/can be completely in sync:
- The `engine` property specifies `the version of node that your stuff works on`: https://docs.npmjs.com/files/package.json#engines
- The `.nvmrc` file defines a specific version, so I don't see a way of allowing 8-10, e.g.

**Comment by Swissbite** [comment]
Then you guys should allow ranges in the package.json config. I know, this is fixed in current master and I know thet the tool is now depcreacted.
But at the time I opened this issue, the two definitions were neither in sync nor in the same range.
